### ISSUE TITLE
brew install alglib does not work!

### ISSUE THREAD

**Issue by SubhenduRakshit** [PhaseTracer/PhaseTracer#1]
Hi, I cannot install alglib in macos from brew!

**Comment by phyzhangyang** [comment]
Could you try to use https://github.com/S-Dafarra/alglib-cmake to install alglib?

**Comment by andrewfowlie** [comment]
@SubhenduRakshit did it work for you?

**Comment by SubhenduRakshit** [comment]
Hi, thanks for your concern. I am trying the 2nd sequence. I am trough till the following command

$cmake --build . --target ALL_BUILD --config Release
make: *** No rule to make target `ALL_BUILD'.  Stop.
$

**Comment by SubhenduRakshit** [comment]
With the first set, I could succeed.
