### ISSUE TITLE
CMake error with NLopt

### ISSUE THREAD

**Issue by phyzhangyang** [PhaseTracer/PhaseTracer#11]
After I installed NLopt lib using "sudo apt install libnlopt-dev", I still have cmake error on a new machine with Ubuntu 20.04.1 LTS:

**CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find NLopt (missing: NLopt_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindNLopt.cmake:33 (find_package_handle_standard_args)
  CMakeLists.txt:22 (find_package)
-- Configuring incomplete, errors occurred!**

This can be fixed by installing NLopt lib manually, following 
https://nlopt.readthedocs.io/en/latest/

**Comment by andrewfowlie** [comment]
Is our https://github.com/PhaseTracer/PhaseTracer/blob/master/cmake/FindNLopt.cmake cmake file out of date?

**Comment by phyzhangyang** [comment]
It seems that Cmake has it's own function of finding Nlopt. I deleted our FindNLopt.cmake, and there is no error information during Cmake process, but the compiler can not find the head file of Nlopt.

**Comment by andrewfowlie** [comment]
Maybe you have an equivalent of FindNLopt.cmake placed somewhere in your system by the apt install libblopt-dev command? And maybe it uses a different variable name for the headers, ${NLopt_INCLUDE_DIRS} versus ${NLopt_INCLUDE_DIR} etc, as these things aren't standardized.

Try `locate *.cmake | grep -i nlopt`

**Comment by phyzhangyang** [comment]
`locate *.cmake | grep -i nlopt`
gives following outputs:
`/usr/lib/x86_64-linux-gnu/cmake/nlopt/NLoptConfig.cmake`
`/usr/lib/x86_64-linux-gnu/cmake/nlopt/NLoptConfigVersion.cmake`
`/usr/lib/x86_64-linux-gnu/cmake/nlopt/NLoptLibraryDepends-none.cmake`
`/usr/lib/x86_64-linux-gnu/cmake/nlopt/NLoptLibraryDepends.cmake`
`/usr/local/lib/cmake/nlopt/NLoptConfig.cmake`
`/usr/local/lib/cmake/nlopt/NLoptConfigVersion.cmake`
`/usr/local/lib/cmake/nlopt/NLoptLibraryDepends-release.cmake`
`/usr/local/lib/cmake/nlopt/NLoptLibraryDepends.cmake`

I think that the ones in `/usr/local/lib/cmake/nlopt` should be generated by installing NLopt manually, while the ones in `/usr/lib/x86_64-linux-gnu/cmake/nlopt/` may be generated by installing NLopt  using apt-get.

`diff /usr/lib/x86_64-linux-gnu/cmake/nlopt/NLoptConfig.cmake /usr/local/lib/cmake/nlopt/NLoptConfig.cmake`
gives
`9c9,11`
` --- set (NLOPT_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/../../../../include")`
` ==set (NLOPT_VERSION "2.6.2") `
` ==set (NLOPT_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/../../../include")`

**Comment by phbasler** [comment]
Hi, 

Through the Issue [BSMPT Issue 24](https://github.com/phbasler/BSMPT/issues/24), reported by @phyzhangyang , I noticed that the apt and brew installs come with their own cmake files. 
You can skip the set(NLOPT_INCLUDE_DIRS) part if you add the correct target_library, in my case this was 

`if(TARGET NLopt::nlopt)
    target_link_libraries(Minimizer PUBLIC NLopt::nlopt)
  else()
    target_link_libraries(Minimizer PUBLIC NLopt::nlopt_cxx)
  endif()` 


The nlopt_cxx is necessary because in Ubuntu you have nlopt-dev and nlopt-cxx-dev, which install those targets. But either one is fine.

**Comment by phyzhangyang** [comment]
Hi Philipp,

Thanks for the suggestion.
 
I found that the real reason of my error is that I need to use 
`apt install libnlopt-cxx-dev`
instead of 
`apt install libnlopt-dev`
on Ubuntu after 19.
