### ISSUE TITLE
[Suggestion] Report subcritical temperatures, which are missed for newly appearing 'truer' vacua.

### ISSUE THREAD

**Issue by LachlanMorris** [PhaseTracer/PhaseTracer#14]
The current method of finding critical transitions misses cases where a phase p_i appears (as temperature is decreasing) that has a lower energy than some pre-existing (i.e. at higher temperature) phase p_j, and V(p_i(T)) < V(p_j(T)) for all T within the overlap window of the two phases.

Although there is no critical temperature -- and therefore critical transition -- between these phases, there is a non-vanishing probability of transitioning from the higher energy phase p_j to the lower energy phase p_i.

My suggestion is to store subcritical transitions as well. This could be done by checking if a phase has lower energy than any other phase when it first appears. Such subcritical transitions could be important in identifying the correct transition path from high temperature to low temperature.

**Comment by andrewfowlie** [comment]
I think this has been done for the v2 release.
