### ISSUE TITLE
Bug in phase_plotter.py

### ISSUE THREAD

**Issue by max-loe** [PhaseTracer/PhaseTracer#17]
Dear developers,

when trying to run `./bin/run_2D_test_model -d ` , I ran into a bug caused by matplotlib version 3.7.0. The problem is that in newer matplotlib versions, the function `inverse_transformed` has been deprecated and can not be used anymore. I was able to fix the bug by replacing line 134 in `.../make_plots/phase_plotter.py` by

`extent = leg.get_window_extent().transformed(ax.transAxes.inverted())`

Best regards,
Maximilian Löschner

**Comment by andrewfowlie** [comment]
Hi Maximilian, thanks for reporting this and finding a solution. We're talking about this line

https://github.com/PhaseTracer/PhaseTracer/blob/266402cd1f657313cbb2f7b3b671115a6c549ae2/make_plots/phase_plotter.py#L134

Would you like to make a PR? The steps would be: Fork this repo. Make a new branch, e.g., python_plot_fix. Make your fix. And lastly make PR.

**Comment by max-loe** [comment]
I followed your instructions and made a PR. Let me know if something went wrong.

**Comment by andrewfowlie** [comment]
Thanks a lot! Merged. Good luck with your physics. Feel free to raise other issues or PRs
