### ISSUE TITLE
Compile error from catch 2 with ubuntu 21.04

### ISSUE THREAD

**Issue by pathron** [PhaseTracer/PhaseTracer#18]
My student is using virtual machine with ubuntu 21.04.  When he does the basic build steps he gets a compile error:

```
$ make
[ 20%] Built target effectivepotential
[ 35%] Built target phasetracer
[ 45%] Built target run_1D_test_model
[ 55%] Built target run_2D_test_model
[ 65%] Built target scan_Z2_scalar_singlet_model
[ 75%] Built target time
Consolidate compiler generated dependencies of target unit_tests
[ 80%] Building CXX object unit_tests/CMakeFiles/unit_tests.dir/catch_main.cpp.o
In file included from /usr/include/signal.h:328,
                 from /home/wangcheng/桌面/PhaseTracer/unit_tests/catch/catch.hpp:7712,
                 from /home/wangcheng/桌面/PhaseTracer/unit_tests/catch_main.cpp:2:
/home/wangcheng/桌面/PhaseTracer/unit_tests/catch/catch.hpp:10453:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
10453 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/sigstksz.h:24:
/usr/include/unistd.h:640:17: note: ‘long int sysconf(int)’ declared here
  640 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
/home/wangcheng/桌面/PhaseTracer/unit_tests/catch/catch.hpp:10512:45: error: size of array ‘altStackMem’ is not an integral constant-expression
10512 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~
make[2]: *** [unit_tests/CMakeFiles/unit_tests.dir/build.make:76：unit_tests/CMakeFiles/unit_tests.dir/catch_main.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:387：unit_tests/CMakeFiles/unit_tests.dir/all] 错误 2
make: *** [Makefile:136：all] 错误 2
```
This can be avoided just by deleting the unit tests from PhaseTracer/CMakeLists.txt (we don't have cmake flag to  avoid building the unit tests?)  and seems to be a bug (or clash with recent ubuntu)  from catch.hpp which is from catch2.  I don't reproduce the problem, but I am still on Ubuntu 20.04.  I am trying to see if this can also be fixed by going to a more recent version (v2 still seems to get updated in parallel with v3 so may have a bug fix like this)  but in v2.13.10 there are many include statements that aren't present in the file we have, so its a bit of a pain.  Maybe @andrewfowlie or @phyzhangyang knows more about this anyway.

**Comment by andrewfowlie** [comment]
Minimal reproducer working on 
```
andrew@andrew-thinkpad:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
andrew@andrew-thinkpad:~$ gcc --version
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Just
```
gcc catch_main.cpp
```
from within unit_tests directory. 

PS we should update our CI tests to catch these issues (https://github.com/PhaseTracer/PhaseTracer/blob/master/.travis.yml). Possibly switch away from travis.

**Comment by andrewfowlie** [comment]
Known issue: https://github.com/catchorg/Catch2/issues?q=MINSIGSTKSZ. Noted first here https://github.com/catchorg/Catch2/issues/2178. Fixed here https://github.com/catchorg/Catch2/blob/devel/docs/release-notes.md#2135

So we need version 2.13.5 at least.

**Comment by andrewfowlie** [comment]
Migrating fully to v3 seems painful. https://github.com/catchorg/Catch2/blob/devel/docs/migrate-v2-to-v3.md#top catch2 was simple because it was single, header only library. Now it's a bigger source, static compiled library. I'll make a PR switching to v2 in which this issue is fixed. We can think about v3 or migrating to another testing suite in the future.

**Comment by andrewfowlie** [comment]
Please test and then merge the `update_catch` branch

**Comment by pathron** [comment]
Thanks Andrew! I'm asking Cheng to test it now.
