### ISSUE TITLE
exit versus throw

### ISSUE THREAD

**Issue by andrewfowlie** [PhaseTracer/PhaseTracer#26]
https://github.com/PhaseTracer/PhaseTracer/blob/8f7520cd22a34c190bf7074781e193841c616e4e/src/gravwave_calculator.cpp#L199

Why do we use exit here (and in several places in the same file)? It might be better two throw a exception, so that in principle in can be caught and the program can carry on. Think of running a scan using PhaseTracer.

**Comment by pathron** [comment]
I strongly agree these should be thrown, not just exits.  To be fair the frequency and vw ones are things that shouldn't happen during a scan, only by a user mistake in constructing the object or inputting data at the command line.  But then throwing an error and catching it in our user input and writing to terminal  e.g. for the bubble wall velocity one "You must enter a bubble wall velocity between 0 and 1" is nicer.  I am not sure about the one about dSdT or sum_spectrums.  If the latter is something that we should never have in our code and can only be a bug, we could also consider an assert  https://www.programiz.com/cpp-programming/assertions

**Comment by andrewfowlie** [comment]
Alight. How about for now, let's replace 

```
LOG(fatal) < msg;
exit(EXIT_FAILURE); 
```

with

```
#include <stdexcept>
.
.
.
throw std::runtime_error(msg);
```

at the same time, let's change this

https://github.com/PhaseTracer/PhaseTracer/blob/8f7520cd22a34c190bf7074781e193841c616e4e/src/gravwave_calculator.cpp#L299

to 

`LOG(debug)
`

**Comment by andrewfowlie** [comment]
This is somewhat fixed in https://github.com/PhaseTracer/PhaseTracer/commit/a70b43b07acfa235b656f679fc5f7c4166bb63d0

At some point, someone might want to see if these throws are better moved somewhere else, e.g., to setters
