### ISSUE TITLE
typo in formula for alpha

### ISSUE THREAD

**Issue by andrewfowlie** [PhaseTracer/PhaseTracer#27]
https://github.com/PhaseTracer/PhaseTracer/blob/b242bb4746444f4675242e503ea46ad2a70f2297/src/gravwave_calculator.cpp#L90

that must be a typo, but is it supposed to be 1 - 2 or 2 - 1?

**Comment by phyzhangyang** [comment]
Yes. It has been fixed. It does not affect current examples, because we only use this one:
get_alpha(const Eigen::VectorXd &vacuum_1, const Eigen::VectorXd &vacuum_2, double T)
