### ISSUE TITLE
BSMPT Update v2.0

### ISSUE THREAD

**Issue by JonasMueller1991** [PhaseTracer/PhaseTracer#7]
Dear all,
we want to draw your attention to our updated version of BSMPT to BSMPT v2.0. Beside the inclusion of additional calculations, several interfaces of functions have changed compared to the previous version. Your test routine might not work with the updated BSMPT version. As a side remark, from now on it is also possible to include BSMPT as a cmake package simplifying the linking of BSMPT. 

With best regards,
Jonas Mueller

**Comment by pathron** [comment]
Thanks for letting us know Jonas!  I saw the BSMPT 2.0 manual, congrats on getting it out. We will discuss how to update to be compatible with BSMPT 2.0

**Comment by phyzhangyang** [comment]
Hi Jonas,

We have upgraded BSMPT used in PhaseTracer to V2.1.

Best,
Yang
