### ISSUE TITLE
Tag phase with deepest zero-temperature minimum

### ISSUE THREAD

**Issue by andrewfowlie** [PhaseTracer/PhaseTracer#8]
Hi guys

I wanted to suggest a feature for phase tracer. I'm finding that there are quite a few points where there are multiple points that look like they could be the electroweak phase transition. It would be nice to tag phases - like the default could be to tag the deepest phase at t_min and highlight that somehow in the output. You could also tell it which one (s) to tag.

kind regards
Graham

**Comment by andrewfowlie** [comment]
See Sec 5.2.1 of the manual (https://arxiv.org/pdf/2003.02859.pdf). It shouldn't be hard to get that information from the phase objects returned by `get_phases()`

My reluctance to add this to the phase object is the following. The deepst one at zero temperature is a property of the set of phases and not of any individual phase. But it's such useful information that I would suggest a `Phase get_deepest_phase_at_T(double T)` method that returned the deepest phase at any given temperature T

**Comment by andrewfowlie** [comment]
Actually it could just be a function rather than a method of the PhaseFinder class

**Comment by phyzhangyang** [comment]
I'm not clear what this can be used for, but it is easy to add this function. I will do it.

**Comment by andrewfowlie** [comment]
Thanks Yang. Don't you think it's useful? Wouldn't you often want to know the phase with the deepest minima at T = 0 or T = something else?

**Comment by phyzhangyang** [comment]
Have added 
std::vector< Phase > get_phases_at_T(double T)
and 
Phase get_deepest_phase_at_T(double T).
